// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrpELbr0ejdRTXsHLf1Ny_izSurlkoo_o',
    appId: '1:389517956549:web:be187fbe6f9ade1387e7ac',
    messagingSenderId: '389517956549',
    projectId: 'terrafarm-378218',
    authDomain: 'terrafarm-378218.firebaseapp.com',
    storageBucket: 'terrafarm-378218.appspot.com',
    measurementId: 'G-QP3DR51SFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHLMhmXm75l7Vmh-JxQZ3xlwUc6Lm87Eo',
    appId: '1:389517956549:android:8e25772fa7c4fc7787e7ac',
    messagingSenderId: '389517956549',
    projectId: 'terrafarm-378218',
    storageBucket: 'terrafarm-378218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9pRw38mPNV3e_aKbJt10i7xALI_WVQU',
    appId: '1:389517956549:ios:ed471d25934d0f3387e7ac',
    messagingSenderId: '389517956549',
    projectId: 'terrafarm-378218',
    storageBucket: 'terrafarm-378218.appspot.com',
    iosClientId: '389517956549-7j8djai8nq13r1ed099mtkihejjtr40o.apps.googleusercontent.com',
    iosBundleId: 'com.example.apaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh9pRw38mPNV3e_aKbJt10i7xALI_WVQU',
    appId: '1:389517956549:ios:ed471d25934d0f3387e7ac',
    messagingSenderId: '389517956549',
    projectId: 'terrafarm-378218',
    storageBucket: 'terrafarm-378218.appspot.com',
    iosClientId: '389517956549-7j8djai8nq13r1ed099mtkihejjtr40o.apps.googleusercontent.com',
    iosBundleId: 'com.example.apaApp',
  );
}
