// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSVXiHQZzxtLqHNoBNRyv9fEgjI4_txiQ',
    appId: '1:180246453185:web:55a8298bd9d6a0514cad40',
    messagingSenderId: '180246453185',
    projectId: 'apa-frontend-dd36c',
    authDomain: 'apa-frontend-dd36c.firebaseapp.com',
    storageBucket: 'apa-frontend-dd36c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfJh6MO267y_hGyg-u4tE3XNERKyALebs',
    appId: '1:180246453185:android:343852f1a010ac534cad40',
    messagingSenderId: '180246453185',
    projectId: 'apa-frontend-dd36c',
    storageBucket: 'apa-frontend-dd36c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVA4F9t8j8zw1syB2w7XHNDviI6HOPs8',
    appId: '1:180246453185:ios:0bc7a512a552fd7d4cad40',
    messagingSenderId: '180246453185',
    projectId: 'apa-frontend-dd36c',
    storageBucket: 'apa-frontend-dd36c.appspot.com',
    iosClientId: '180246453185-8oaim7a1f8btoo3tldkdvmdk8uf5us05.apps.googleusercontent.com',
    iosBundleId: 'com.example.apaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVA4F9t8j8zw1syB2w7XHNDviI6HOPs8',
    appId: '1:180246453185:ios:0bc7a512a552fd7d4cad40',
    messagingSenderId: '180246453185',
    projectId: 'apa-frontend-dd36c',
    storageBucket: 'apa-frontend-dd36c.appspot.com',
    iosClientId: '180246453185-8oaim7a1f8btoo3tldkdvmdk8uf5us05.apps.googleusercontent.com',
    iosBundleId: 'com.example.apaApp',
  );
}
